### PR TITLE
Feature/async

### PR DESCRIPTION
**Pull request by stelcheck**
Adding just-in-time reporting. So instead of getting your results at 

serviceInterval: 20000,
    serviceDelay: 500

== 20000 + 500ms,

you can get it as soon as ALL results are in. This allow to set serviceDelay higher (basically, as a timeout value),  but still get more frequent updates.

### CODE REVIEW

**Comment by stelcheck** [comment]
Have also rebased this one.

**Comment by stelcheck** [comment]
Been a couple months, but... could this be merged? Sounds to me like it would be a nice way to keep the dashboard more accurate.

**Comment by obazoud** [comment]
@stelcheck it is ok for me, but I can't merge this pull request, a lot of conflicts.
Could you be send me a pull request from lastest master with only 1 commit ?

**Comment by obazoud** [comment]
@stelcheck it is ok for me, but I can't merge this pull request, a lot of conflicts.
Could you be send me a pull request from lastest master with only 1 commit ?

**Pull request closed without merging**
