### PR TITLE
Modularization, dynamic service add/remove, refactoring and (possibly) bugfixing

### PR DESCRIPTION
**Pull request by stelcheck**
First, my apologies. I REALLY went overboard with changing the code. Rest assured though that as far as I have seen it should all work.

This addresses mainly https://github.com/obazoud/statusdashboard/issues/35 and https://github.com/obazoud/statusdashboard/issues/34. I have already wrote a first integration in my application, and the service list basically updates itself using node-mdns. Pretty cool stuff :). Now I will be using the events from the api to enable and disable other higher level service across our architecture with it.

It also, I think, makes the code more readable, and standard (I jshinted the files I modified as I go). I fixed a few things here and there (see commit log).

I would still need to fix a thing or two before really having something ready (for instance, moving default config to server.js so that it is taken in consideration when starting statusdashboard from code), but I thought I should let you guys know of what I had done in terms of changes.

Again, apologies for the aggressive rewrites, but I hope you will find value in what is in this.

### CODE REVIEW

**Comment by chamerling** [comment]
Not tested but looks like a very nice contribution!

**Comment by obazoud** [comment]
Thanks for your contribution.
I need time to test.

**Comment by stelcheck** [comment]
No problem. Let me know if I can clarify anything

Kind regards,

**Comment by obazoud** [comment]
After some tests, I think there is a bug in ftp check.
I can see in my log

```
 TypeError: Object [object Object] has no method 'command'
```

I think it is line 50

```
var ftp = new Ftp(service, stream);
```

this 'ftp object' does not have a command function.

With demo settings, it seems to block other checks.

**Comment by stelcheck** [comment]
My bad. Just pushed a fix for that.

On Tue, Jan 22, 2013 at 7:27 AM, Olivier Bazoud notifications@github.comwrote:

> After some tests, I think there is a bug in ftp check.
> I can see in my log
> 
>  TypeError: Object [object Object] has no method 'command'
> 
> I think it is line 50
> 
> var ftp = new Ftp(service, stream);
> 
> this 'ftp object' does not have a command function.
> 
> With demo settings, it seems to block other checks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/obazoud/statusdashboard/pull/36#issuecomment-12520974.

## 

http://www.wizcorp.jp/Marc Trudel-Belisle

## Chief Technology Officer | Wizcorp Inc. http://www.wizcorp.jp/

TECH . GAMING . OPEN-SOURCE WIZARDS+ 81
3-4550-1448|Websitehttp://www.wizcorp.jp/
|Twitter https://twitter.com/Wizcorp|Facebookhttp://www.facebook.com/Wizcorp
|LinkedIn http://www.linkedin.com/company/wizcorp

**Comment by obazoud** [comment]
Looks great.
@stelcheck thank you for this awesome contribution

**Comment by obazoud** [comment]
0.6.0 published: https://npmjs.org/package/statusdashboard

**Comment by stelcheck** [comment]
Awesome! Thanks.

Kind regards,

**Pull request merged**
